### ISSUE TITLE
Demo uploads with zero bytes

### ISSUE THREAD

**Issue by ttftw** [digitalnodecom/node-red-contrib-generic-s3#74] opened 2023-10-11 18:38 UTC
I'm using your example dashboard from 1.11.3 and have an s3 Space through Digital Ocean which is supposed to be s3 compatible. 

When I run your node to put an object, the file is created on DO, but the file is 0 bytes. I don't have an Amazon account to test this with s3 directly, but I wanted to check here to make sure there's not something else I'm missing before talking with DO about what might be wrong.

I've also tries to send an image as bytes and anything I try to send shows up on their end as 0 bytes.

```js
// File contents, in this example object that is later stringified in json
const testJson = {
    "Data": {
        "Exists": true,
        "Testing": "Dummy data"
    },
    "Something": "Other dummy data",
    "Changes": true
}

// Parameters that are later passed to create the object
const objectToCreate = {
    Key: 'TestFile.json',
    ContentType: 'application/json',
    Body: JSON.stringify(testJson),
}

// Object's unique identifier
msg.key = objectToCreate.Key;
// Content type of the object
msg.contentType = objectToCreate.ContentType;
// Object body
msg.body = objectToCreate.Body;
// Is stream flag for the body. Please refer to the docs for how to streamify the body
msg.stream = false;
// Upsert flag for the node
msg.upsert = true;

return msg;

**Comment by ttftw** [comment] 2023-10-12 00:45
I used this same code to Amazon S3 and it still is uploading 0 bytes so I must be missing something else here

**Comment by rristov60** [comment] 2023-10-28 17:48
Hi @ttftw, sorry for the delayed response. I checked the examples and unfortunately seems that they are not up to date and for some nodes there are none, which will be patched. Right now I will try to reproduce your issue, and will get back at you with the results from that

**Comment by rristov60** [comment] 2023-10-28 21:04
Quick update on this @ttftw. I've tried to recreate your issue using [Scaleway](https://www.scaleway.com/en/), but unfortunately I was not able to. Just quick note when you said that you've tried to send an image as bytes, I hope that you updated the **ContentType** header as well, because that plays crucial role. But, when I tried to even mismatch the header(with Scaleway at least), the object was still uploaded with the correct amount of bytes, the retrieving of the object had some issues. Even though this is out of scope of this issue, you can find most common used ContentType header values [here](https://stackoverflow.com/questions/23714383/what-are-all-the-possible-values-for-http-content-type-header), and the list of all available header values [here](https://www.iana.org/assignments/media-types/media-types.xhtml). 

Next step that is to try and test with different providers, but I can say that the example successfully uploads **_93 bytes_** when using Scaleway. 

Also I am not sure exactly what your configuration is (if you can provide a sample from the flow you are using that would be great, as it will allow me to easily recreate the issue), but please keep in mind that priority is always given to the input fields on the node itself (UI input fields).

**Comment by rristov60** [comment] 2023-11-10 19:08
Hi @ttftw, just wanted to follow up if there is any update from your side on this ?

**Comment by trajche** [comment] 2023-12-26 15:27
Closing this due to inability to replicate.

**Closed by trajche** 2023-12-26 15:27 UTC
